sudo: false
language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=ralscha23

install: 
  - chmod 700 ./mvnw
  - cd wamp2spring-core
  - ../mvnw install -Dfindbugs.skip=true -B  
  - cd ../wamp2spring-servlet
  - ../mvnw install -Dfindbugs.skip=true -B  
  - cd ../wamp2spring-reactive
  - ../mvnw install -Dfindbugs.skip=true -B  
  - cd ../wamp2spring-security-core
  - ../mvnw install -Dfindbugs.skip=true -B
  - cd ../wamp2spring-security-servlet
  - ../mvnw test -Dfindbugs.skip=true -B
  - cd ../wamp2spring-session-servlet
  - ../mvnw test -Dfindbugs.skip=true -B

after_success:
  - python addsettings.py
  - cd wamp2spring-core
  - ../mvnw clean deploy -DskipTests=true -Dfindbugs.skip=true --settings ~/.m2/mySettings.xml
  - cd ../wamp2spring-servlet
  - ../mvnw clean deploy -DskipTests=true -Dfindbugs.skip=true --settings ~/.m2/mySettings.xml
  - cd ../wamp2spring-reactive
  - ../mvnw clean deploy -DskipTests=true -Dfindbugs.skip=true --settings ~/.m2/mySettings.xml
  - cd ../wamp2spring-security-core
  - ../mvnw clean deploy -DskipTests=true -Dfindbugs.skip=true --settings ~/.m2/mySettings.xml
  - cd ../wamp2spring-security-servlet
  - ../mvnw clean deploy -DskipTests=true -Dfindbugs.skip=true --settings ~/.m2/mySettings.xml
  - cd ../wamp2spring-session-servlet
  - ../mvnw clean deploy -DskipTests=true -Dfindbugs.skip=true --settings ~/.m2/mySettings.xml
  
cache:
  directories:
  - "$HOME/.m2"
