sudo: false
language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=ralscha23

install: 
  - chmod 700 ./mvnw
  - ./mvnw test -Dfindbugs.skip=true -B

after_success:
  - python addsettings.py
  - ./mvnw clean deploy -DskipTests=true -Dfindbugs.skip=true --settings ~/.m2/mySettings.xml
  
cache:
  directories:
  - "$HOME/.m2"
